services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: laravel_app
        restart: unless-stopped
        working_dir: /var/www
        volumes:
            - .:/var/www
        networks:
            - laravel_network
        depends_on:
            - postgres
        ports:
            - "9000:9000"

    postgres:
        image: postgres:15
        container_name: postgres_db
        restart: unless-stopped
        environment:
            - POSTGRES_DB=laravel_entrance_test
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=123456
        networks:
            - laravel_network
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"

    nginx:
        image: nginx:alpine
        container_name: nginx
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - .:/var/www
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        networks:
            - laravel_network
        depends_on:
            - app

networks:
    laravel_network:
        driver: bridge

volumes:
    postgres_data:
